---
title: "participation 6"
author: "Emily Arnold"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

req.packages <- c("leaflet", "tidycensus", "ggthemes", "tidyverse", "ggthemes", "ggExtra", "scales")

'%notin%' <- Negate('%in%')

if(any(installed.packages() %notin% req.packages)){
  missing.packages <- which(req.packages %notin% installed.packages())
  install.packages(req.packages[missing.packages])
}

eval(
  parse(
    text = paste0('library(',req.packages, ')')
  )
)



```

#tidy census
### Basic Usage

```{r setup, include=FALSE}
# if(!file.exists("~/.Rprofile"))
#   file.create("~/.Rprofile")
# file.edit("~/.Rprofile")

source("~/.Rprofile")

census_api_key(key = census.api.key, install = TRUE, overwrite = TRUE)


```

"get_acs" 5-year American community survey API
"get_decennial" - full census API


```{r loading in us census data}

census.2000 <- load_variables(year = 2000, "sf1", cache = TRUE) #caches data locally

DT::datatable(
  head(
    census.2000, n = 200
  )
)

```

```{r looking at acs data}
acs.2017 <- load_variables(year = 2017, dataset = 'acs1', cache = TRUE)

DT::datatable(
  head(
    acs.2017, n = 20
  )
)
```

```{r loading in transportation data}

women <- get_acs(geography = "county",
                state = "NY",
                variables = "B01001_026",
                keep_geo_vars = TRUE,
                geometry = TRUE)

men <- get_acs(geography = "county",
                state = "NY",
                variables = "B01001_002",
                keep_geo_vars = TRUE,
                geometry = TRUE)

colnames(women)[12] <- "women"
colnames(men)[12] <- "men"

# men$variable <- NULL
# women$variable <- NULL
# men$moe <- NULL
# women$moe <- NULL

men <- men[,c("NAME.x", "estimate")]
men$geometry <- NULL


total <- merge(women, men, by = c("NAME.x"))

total$ratio <- total$women/total$estimate

```



```{r visualization}
total %>% 
  top_n(15, ratio) %>% 
  mutate(county = as.factor(NAME.x)) %>% 
  ggplot(data = ., aes(y = ratio, x = reorder(county, ratio)))+
  geom_point()+
  theme_tufte()+
  theme(axis.title = element_blank(), axis.ticks = element_blank(), axis.text.x = element_text(angle = 45))+
  ggtitle(label = "Ratio of Women to Men by county")


```


```{r}

sjfc <- leaflet() %>% 
  addTiles() %>%  #add default map tiles
  addMarkers(lng = -77.509, lat = 43.1157, popup = "SJFC::GDAT515")

sjfc

```


```{r}
color.pal <- colorNumeric(palette = "viridis", domain = total$ratio)
```


```{r}
gender.map <- leaflet(data = total) %>% 
  addTiles() %>% 
  setView(lng = -77.509, lat = 43.1157, zoom = 8) %>% 
  addPolygons(fillColor = ~color.pal(total$ratio),
              fillOpacity = 0.7,
              fill = TRUE,
              weight = 0.7,
              smoothFactor = 0.3,
              color = "black",
              highlight = highlightOptions(weight = 2,
                                           color = "Black",
                                           fillOpacity = 0.9,
                                           bringToFront = FALSE),
              popup = ~paste("<b>County: <b>", NAME.x, "<br>",
                             "<b>Gender Ratio: <b>", ratio)) %>% 
              addLegend(position = "topleft",
                        pal = color.pal, 
                        values = total$ratio,
                        title = "Gender Ratio")

# gender.map %>% 
#   addAwesomeMarkers(lng = -77, lat = 43, icon = awesomeIcons())
```

